[package]
name = "failover-shim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Automatic failover for HA databases"

[dependencies]
shim-core = { path = "../shim-core" }
anyhow.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
prometheus.workspace = true
parking_lot.workspace = true
redis.workspace = true
