[package]
name = "queue-shim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "QueueShimShim for EvergreenShims"

[dependencies]
shim-core = { path = "../shim-core" }
anyhow.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
prometheus.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
