[package]
name = "alerting-shim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "AlertingShimShim for EvergreenShims"

[dependencies]
shim-core = { path = "../shim-core" }
anyhow.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
prometheus.workspace = true
uuid.workspace = true
chrono.workspace = true

[dev-dependencies]
tempfile.workspace = true
temp-env.workspace = true
